import { addDays, firstDayOfMonth, getMonthWeeks, monthKeyOf, nowISO, systemToday } from '@/domain/dates';
import type { Category, HouseholdData, Transaction } from '@/domain/types';

/**
 * Dataset de PREVISUALIZACIÓN DE INTERFAZ (solo desarrollo).
 *
 * No es la app: es un banco de pruebas de diseño para revisar pantallas sin
 * levantar Supabase. La fuente de verdad de SEMILLA es siempre la base de datos.
 * Se activa con NEXT_PUBLIC_SEMILLA_PREVIEW=1 y nunca debe usarse en producción.
 */

const HOUSEHOLD = 'preview-household';
const CARMELO = 'preview-carmelo';
const SARA = 'preview-sara';

const stamp = { createdAt: nowISO(), updatedAt: nowISO() };

function category(
  id: string,
  name: string,
  emoji: string,
  tone: number,
  quick: boolean,
  subs: string[],
): Category {
  return {
    id,
    householdId: HOUSEHOLD,
    name,
    emoji,
    tone,
    priority: 'flexible',
    quick,
    position: tone,
    archived: false,
    subcategories: subs.map((sub, index) => ({
      id: `${id}-${index}`,
      householdId: HOUSEHOLD,
      categoryId: id,
      name: sub,
      position: index,
      archived: false,
    })),
    ...stamp,
  };
}

export function buildPreviewData(): HouseholdData {
  const today = systemToday();
  const month = monthKeyOf(today);
  const start = firstDayOfMonth(month);
  const day = (offset: number) => addDays(start, offset);
  /* Días contados hacia atrás desde hoy, para que la semana en curso tenga movimientos. */
  const back = (days: number) => addDays(today, -days);
  const weeks = getMonthWeeks(month);

  const categories = [
    category('cat-food', 'Alimentación', '🛒', 0, true, ['Supermercado', 'Fruta', 'Panadería']),
    category('cat-transport', 'Transporte', '⛽', 1, true, ['Gasolina', 'Parking', 'Taller']),
    category('cat-home', 'Vivienda', '🏠', 2, true, ['Electricidad', 'Internet', 'Reparaciones']),
    category('cat-kids', 'Niños y educación', '👶', 3, true, ['Colegio', 'Comedor', 'Actividades']),
    category('cat-health', 'Salud', '❤️', 4, true, ['Farmacia', 'Fisioterapia', 'Dentista']),
    category('cat-fun', 'Ocio', '🍽️', 5, true, ['Restaurantes', 'Cine', 'Escapadas']),
    category('cat-shop', 'Compras', '🛍️', 6, true, ['Amazon', 'Regalos', 'Tecnología']),
    category('cat-help', 'Ayuda doméstica', '🧺', 7, false, ['Limpieza', 'Cuidadora']),
    category('cat-insurance', 'Seguros', '🛡️', 2, false, ['Hogar', 'Coche']),
  ];

  const expenseOn = (
    id: string,
    when: string,
    amount: number,
    description: string,
    categoryId: string,
    subcategoryId: string | null,
    owner: string,
    extra = false,
    necessary = true,
  ): Transaction => ({
    id,
    householdId: HOUSEHOLD,
    kind: 'expense',
    amount,
    date: when,
    description,
    note: '',
    accountId: 'acc-main',
    paymentMethodId: 'pm-card',
    ownerUserId: owner,
    createdByUserId: owner,
    updatedByUserId: null,
    plannedId: null,
    tagIds: [],
    categoryId,
    subcategoryId,
    merchantId: null,
    necessity: necessary ? 'necessary' : 'discretionary',
    frequency: extra ? 'extraordinary' : 'ordinary',
    expectedAmount: null,
    ...stamp,
  });

  const allTransactions: Transaction[] = [
    {
      id: 'inc-1',
      householdId: HOUSEHOLD,
      kind: 'income',
      amount: 541600,
      date: day(0),
      description: 'Nómina',
      note: '',
      accountId: 'acc-main',
      paymentMethodId: 'pm-account',
      ownerUserId: CARMELO,
      createdByUserId: CARMELO,
      updatedByUserId: null,
      plannedId: null,
      tagIds: [],
      sourceId: 'src-carmelo',
      recurrence: 'recurring',
      expectedAmount: 530000,
      ...stamp,
    },
    {
      id: 'inc-2',
      householdId: HOUSEHOLD,
      kind: 'income',
      amount: 185000,
      date: day(0),
      description: 'Nómina',
      note: '',
      accountId: 'acc-main',
      paymentMethodId: 'pm-account',
      ownerUserId: SARA,
      createdByUserId: SARA,
      updatedByUserId: null,
      plannedId: null,
      tagIds: [],
      sourceId: 'src-sara',
      recurrence: 'recurring',
      expectedAmount: 185000,
      ...stamp,
    },
    {
      id: 'inc-3',
      householdId: HOUSEHOLD,
      kind: 'income',
      amount: 71600,
      date: day(4),
      description: 'Alquiler',
      note: '',
      accountId: 'acc-main',
      paymentMethodId: 'pm-account',
      ownerUserId: CARMELO,
      createdByUserId: CARMELO,
      updatedByUserId: null,
      plannedId: null,
      tagIds: [],
      sourceId: 'src-rent',
      recurrence: 'recurring',
      expectedAmount: 71600,
      ...stamp,
    },
    expenseOn('exp-1', back(0), 8742, 'Mercadona', 'cat-food', 'cat-food-0', SARA),
    expenseOn('exp-2', back(1), 6200, 'Repsol', 'cat-transport', 'cat-transport-0', CARMELO),
    expenseOn('exp-3', day(2), 66500, 'Colegio', 'cat-kids', 'cat-kids-0', CARMELO),
    expenseOn('exp-4', back(2), 3200, 'Farmacia', 'cat-health', 'cat-health-0', SARA),
    expenseOn('exp-5', back(3), 9120, 'Mercadona', 'cat-food', 'cat-food-0', SARA),
    expenseOn('exp-6', back(4), 6000, 'Limpieza', 'cat-help', 'cat-help-0', CARMELO),
    expenseOn('exp-7', back(5), 5850, 'Repsol', 'cat-transport', 'cat-transport-0', CARMELO),
    expenseOn('exp-8', back(6), 4230, 'Amazon', 'cat-shop', 'cat-shop-0', SARA, false, false),
    expenseOn('exp-9', back(8), 7640, 'Mercadona', 'cat-food', 'cat-food-0', SARA),
    expenseOn('exp-10', back(9), 5400, 'Restaurante', 'cat-fun', 'cat-fun-0', CARMELO, false, false),
    expenseOn('exp-11', back(10), 8000, 'Cuidadora', 'cat-help', 'cat-help-1', SARA),
    expenseOn('exp-12', back(11), 12000, 'Fisio', 'cat-health', 'cat-health-1', CARMELO, true),
    expenseOn('exp-13', back(12), 38000, 'Seguro hogar', 'cat-insurance', 'cat-insurance-0', CARMELO, true),
    {
      id: 'sav-1',
      householdId: HOUSEHOLD,
      kind: 'saving',
      amount: 30000,
      date: back(7),
      description: 'Ahorro mensual',
      note: '',
      accountId: 'acc-savings',
      paymentMethodId: null,
      ownerUserId: CARMELO,
      createdByUserId: CARMELO,
      updatedByUserId: null,
      plannedId: null,
      tagIds: [],
      pocketId: 'pocket-emergency',
      direction: 'in',
      ...stamp,
    },
    {
      id: 'debt-1',
      householdId: HOUSEHOLD,
      kind: 'debtPayment',
      amount: 50000,
      date: back(4),
      description: 'Amortización',
      note: '',
      accountId: 'acc-main',
      paymentMethodId: 'pm-account',
      ownerUserId: CARMELO,
      createdByUserId: CARMELO,
      updatedByUserId: null,
      plannedId: null,
      tagIds: [],
      debtId: 'debt-ing',
      paymentType: 'extra',
      ...stamp,
    },
  ];
  const transactions = allTransactions.filter((transaction) => transaction.date <= today);

  return {
    household: {
      id: HOUSEHOLD,
      name: 'Familia García',
      createdBy: CARMELO,
      locale: 'es-ES',
      currency: 'EUR',
      timeZone: 'Europe/Madrid',
      createdAt: nowISO(),
    },
    settings: { householdId: HOUSEHOLD, onboarded: true, demoDataLoaded: true, lastBackupAt: null },
    members: [
      {
        id: 'member-carmelo',
        householdId: HOUSEHOLD,
        userId: CARMELO,
        name: 'Carmelo',
        initials: 'C',
        role: 'owner',
        accent: 'forest',
        email: 'carmelo@semilla.test',
      },
      {
        id: 'member-sara',
        householdId: HOUSEHOLD,
        userId: SARA,
        name: 'Sara',
        initials: 'S',
        role: 'member',
        accent: 'leaf',
        email: 'sara@semilla.test',
      },
    ],
    accounts: [
      {
        id: 'acc-main',
        householdId: HOUSEHOLD,
        name: 'Cuenta principal',
        type: 'main',
        openingBalance: 412000,
        balanceDate: addDays(start, -1),
        countsAsAvailable: true,
        position: 0,
        archived: false,
        ...stamp,
      },
      {
        id: 'acc-savings',
        householdId: HOUSEHOLD,
        name: 'Cuenta de ahorro',
        type: 'savings',
        openingBalance: 843000,
        balanceDate: addDays(start, -1),
        countsAsAvailable: false,
        position: 1,
        archived: false,
        ...stamp,
      },
    ],
    paymentMethods: [
      {
        id: 'pm-account',
        householdId: HOUSEHOLD,
        name: 'Cuenta',
        type: 'account',
        accountId: 'acc-main',
        position: 0,
        archived: false,
        ...stamp,
      },
      {
        id: 'pm-card',
        householdId: HOUSEHOLD,
        name: 'Tarjeta',
        type: 'card',
        accountId: 'acc-main',
        position: 1,
        archived: false,
        ...stamp,
      },
      {
        id: 'pm-cash',
        householdId: HOUSEHOLD,
        name: 'Efectivo',
        type: 'cash',
        accountId: null,
        position: 2,
        archived: false,
        ...stamp,
      },
      {
        id: 'pm-bizum',
        householdId: HOUSEHOLD,
        name: 'Bizum',
        type: 'bizum',
        accountId: 'acc-main',
        position: 3,
        archived: false,
        ...stamp,
      },
    ],
    categories,
    tags: ['Salud', 'Colegio', 'Casa', 'Viaje'].map((name, index) => ({
      id: `tag-${index}`,
      householdId: HOUSEHOLD,
      name,
      archived: false,
      ...stamp,
    })),
    merchants: [
      {
        id: 'merch-merca',
        householdId: HOUSEHOLD,
        name: 'Mercadona',
        normalized: 'mercadona',
        defaultCategoryId: 'cat-food',
        defaultSubcategoryId: 'cat-food-0',
        uses: 6,
        lastUsedAt: nowISO(),
        ...stamp,
      },
      {
        id: 'merch-repsol',
        householdId: HOUSEHOLD,
        name: 'Repsol',
        normalized: 'repsol',
        defaultCategoryId: 'cat-transport',
        defaultSubcategoryId: 'cat-transport-0',
        uses: 4,
        lastUsedAt: nowISO(),
        ...stamp,
      },
    ],
    incomeSources: [
      {
        id: 'src-carmelo',
        householdId: HOUSEHOLD,
        name: 'Nómina Carmelo',
        ownerUserId: CARMELO,
        expectedAmount: 530000,
        recurring: true,
        position: 0,
        archived: false,
        ...stamp,
      },
      {
        id: 'src-sara',
        householdId: HOUSEHOLD,
        name: 'Nómina Sara',
        ownerUserId: SARA,
        expectedAmount: 185000,
        recurring: true,
        position: 1,
        archived: false,
        ...stamp,
      },
      {
        id: 'src-rent',
        householdId: HOUSEHOLD,
        name: 'Alquiler',
        ownerUserId: null,
        expectedAmount: 71600,
        recurring: true,
        position: 2,
        archived: false,
        ...stamp,
      },
      {
        id: 'src-other',
        householdId: HOUSEHOLD,
        name: 'Otros',
        ownerUserId: null,
        expectedAmount: null,
        recurring: false,
        position: 3,
        archived: false,
        ...stamp,
      },
    ],
    transactions: transactions.sort((a, b) => b.date.localeCompare(a.date)),
    monthlyBudgets: [
      {
        id: 'mb-1',
        householdId: HOUSEHOLD,
        month,
        planned: 685000,
        categoryLimits: [
          { id: 'lim-1', categoryId: 'cat-food', amount: 74000 },
          { id: 'lim-2', categoryId: 'cat-transport', amount: 42000 },
          { id: 'lim-3', categoryId: 'cat-fun', amount: 10000 },
        ],
        ...stamp,
      },
    ],
    weeklyBudgets: weeks.map((week, index) => ({
      id: `wb-${week.index}`,
      householdId: HOUSEHOLD,
      month,
      weekIndex: week.index,
      planned: index === 0 ? 40000 : week.partial ? 21500 : 47000,
      categoryLimits: [],
      ...stamp,
    })),
    plannedItems: [
      {
        id: 'plan-mortgage',
        householdId: HOUSEHOLD,
        name: 'Hipoteca',
        kind: 'debtPayment',
        expectedAmount: 102900,
        frequency: 'monthly',
        dayOfMonth: 5,
        months: null,
        categoryId: null,
        subcategoryId: null,
        sourceId: null,
        debtId: 'debt-mortgage',
        accountId: 'acc-main',
        ownerUserId: null,
        extraordinary: false,
        installments: null,
        active: true,
        notes: '',
        ...stamp,
      },
      {
        id: 'plan-orange',
        householdId: HOUSEHOLD,
        name: 'Orange',
        kind: 'expense',
        expectedAmount: 14000,
        frequency: 'monthly',
        dayOfMonth: 22,
        months: null,
        categoryId: 'cat-home',
        subcategoryId: 'cat-home-1',
        sourceId: null,
        debtId: null,
        accountId: 'acc-main',
        ownerUserId: null,
        extraordinary: false,
        installments: null,
        active: true,
        notes: '',
        ...stamp,
      },
    ],
    pockets: [
      {
        id: 'pocket-emergency',
        householdId: HOUSEHOLD,
        name: 'Fondo de emergencia',
        emoji: '🛡️',
        type: 'savings',
        targetAmount: 1500000,
        targetDate: null,
        openingBalance: 813000,
        accountId: 'acc-savings',
        position: 0,
        archived: false,
        ...stamp,
      },
      {
        id: 'pocket-car',
        householdId: HOUSEHOLD,
        name: 'Coche',
        emoji: '🚗',
        type: 'reserved',
        targetAmount: 150000,
        targetDate: null,
        openingBalance: 60000,
        accountId: 'acc-savings',
        position: 1,
        archived: false,
        ...stamp,
      },
      {
        id: 'pocket-xmas',
        householdId: HOUSEHOLD,
        name: 'Navidad',
        emoji: '🎄',
        type: 'reserved',
        targetAmount: 100000,
        targetDate: null,
        openingBalance: 30000,
        accountId: 'acc-savings',
        position: 2,
        archived: false,
        ...stamp,
      },
    ],
    debts: [
      {
        id: 'debt-mortgage',
        householdId: HOUSEHOLD,
        name: 'Hipoteca',
        type: 'mortgage',
        initialBalance: 21000000,
        balanceAtStart: 8600000,
        trackingStart: addDays(start, -1),
        installment: 102900,
        interestBps: 195,
        startDate: null,
        endDate: null,
        priority: 5,
        notes: '',
        archived: false,
        ...stamp,
      },
      {
        id: 'debt-ing',
        householdId: HOUSEHOLD,
        name: 'ING',
        type: 'loan',
        initialBalance: 2500000,
        balanceAtStart: 1420000,
        trackingStart: addDays(start, -1),
        installment: 47500,
        interestBps: 615,
        startDate: null,
        endDate: null,
        priority: 1,
        notes: '',
        archived: false,
        ...stamp,
      },
    ],
    goals: [
      {
        id: 'goal-1',
        householdId: HOUSEHOLD,
        name: 'Nuestro primer año',
        startDate: start,
        endDate: addDays(start, 364),
        savingsTarget: 1500000,
        extraDebtTarget: 3000000,
        greenWeeksTarget: 40,
        active: true,
        ...stamp,
      },
    ],
    achievements: [
      { id: 'first-seed', unlockedAt: nowISO() },
      { id: 'first-pocket', unlockedAt: nowISO() },
    ],
    weeklyCloses: [],
    monthlyCloses: [],
    quickActions: [],
    invites: [],
  };
}
